import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import UserMenu from "@/components/UserMenu";

export const metadata: Metadata = {
  title: "Titan App",
  description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-between items-center px-6 py-3 border-b">
          <div className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/about">About</Link>
          </div>
          <UserMenu />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
